copy /Y 1.bat                       Export\1.bat
copy /Y start_oo_server.bat         Export\start_oo_server.bat
copy /Y svbsa101k2.odg              Export\svbsa101k2.odg
copy /Y TT_stumuz_TT.odt            Export\TT_stumuz_TT.odt
copy /Y DoDoc.py                    Export\DoDoc.py
copy /Y DoDoc_parameters_parser.py  Export\DoDoc_parameters_parser.py
copy /Y import_uno.py               Export\import_uno.py
copy /Y odg2png.py                  Export\odg2png.py
copy /Y odt2pdf.py                  Export\odt2pdf.py
copy /Y OpenOffice_document.py      Export\OpenOffice_document.py
copy /Y Template.py                 Export\Template.py
copy /Y README.txt                  Export\README.txt
copy /Y stumuz_TT.xml               Export\stumuz_TT.xml
